services:
  webserver:
    image: nginx:1.15.12-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - laravel-production
    depends_on:
      - php-fpm
    restart: unless-stopped
    container_name: prod_webserver

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: production
    env_file:
      - .env
    networks:
      - laravel-production
    depends_on:
      - db
    restart: unless-stopped
    container_name: prod_php

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-production:/var/lib/mysql
    networks:
      - laravel-production
    restart: unless-stopped
    container_name: prod_db

    # healthcheck:
    #   test: ["CMD", "pg_isready"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

networks:
  laravel-production:

volumes:
  db-production:
